name: dantotsu
description: "An Anilist client"

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Application version and build number
version: 1.0.0+1

# Dart SDK constraints
environment:
  sdk: '>=3.4.3 <4.0.0'

# Main dependencies
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  provider: ^6.1.2
  get: ^4.6.6

  # Networking
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  http_interceptor: ^2.0.0
  html: ^0.15.4
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  # JSON Serialization
  json_annotation: ^4.9.0

  # Local Storage
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.5
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  expandable_text: 2.3.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flex_color_scheme: ^8.0.2
  flex_color_picker: ^3.6.0
  flutter_markdown: ^0.7.4+3
  icons_plus: ^5.0.0

  # UI Enhancements
  blur: ^4.0.0
  visibility_detector: ^0.4.0+2
  kenburns_nullsafety: ^1.0.1

  # Platform Specific
  permission_handler: ^11.3.1
  webview_windows: ^0.4.0
  webview_flutter: ^4.10.0

  # Miscellaneous
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  dynamic_color: ^1.7.0
  dart_eval: ^0.7.10
  pseudom: ^1.0.1
  encrypt: ^5.0.3
  xpath_selector_html_parser: ^3.0.1
  js_packer: ^0.0.5
  intl: ^0.19.0
  json_path: ^0.7.4
  freezed_annotation: ^2.0.0
  flutter_rust_bridge: ^2.3.0
  grouped_list: ^6.0.0
  fuzzywuzzy: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  crypto: ^3.0.6
  collection: ^1.19.1
  flutter_web_auth_2: ^4.1.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

  # Code Generation
  hive_generator: ^2.0.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.7
  # riverpod_generator: ^2.6.2
  # isar_generator: ^3.1.0+1
dependency_overrides:
  analyzer: ">=5.2.0 <7.0.0"
  collection: ^1.19.0

# Flutter-specific configurations
flutter:
  uses-material-design: true
  generate: true
  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins_thin.ttf
          weight: 100

  # Assets
  assets:
    - assets/images/logo.png
    - assets/svg/bmc-button.svg
    - assets/svg/anilist.svg
    - assets/svg/discord.svg
    - assets/svg/kitsu.svg
    - assets/svg/mal.svg


# Flutter Launcher Icons Configuration
# dart run flutter_launcher_icons
flutter_icons:
  ios: true
  image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
  macos:
    generate: true
    image_path: "assets/images/logo.png"
